spring:
  data:
    mongodb:
      username: root
      password: Mupezeni0102?
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
server:
    port: 8090
