services:
  postgres:
    container_name: ms_pd_sql
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Mupezeni0102?
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - microservices-net
    restart: unless-stopped

  pgadmin:
    container_name: ms_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80
    networks:
      - microservices-net
    restart: unless-stopped

  mongo:
    container_name: ms_mongo_db
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Mupezeni0102?
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db
    networks:
        - microservices-net

#  mongo-express:
#    container_name: ms_mongo_express
#    image: mongo-express
#    restart: unless-stopped
#    depends_on:
#      - mongo
#    environment:
#      ME_CONFIG_MONGODB_SERVER: ms_mongo_db
#      ME_CONFIG_MONGODB_PORT: 27017
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: Mupezeni0102?
#    ports:
#      - "8081:8081"
#    networks:
#        - microservices-net

  mail-dev:
    container_name: ms_mail_dev
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
#    environment:
#      MAILDEV_USERNAME: root
#      MAILDEV_PASSWORD: Mupezeni0102?

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: ms_zookeeper
    ports:
      - "22181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: ms_kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: ms_zookeeper:2181

  zipkin:
    image: openzipkin/zipkin
    container_name: ms_zipkin
    ports:
      - "9411:9411"
    networks:
        - microservices-net


  keycloak:
    container_name: ms_keycloak
    image: quay.io/keycloak/keycloak:latest
    ports:
      - 8080:8080
    environment:
        KEYCLOAK_ADMIN: mupezeni
        KEYCLOAK_ADMIN_PASSWORD: 'Mupezeni0102?'
    networks:
        - microservices-net
    command:
      - "start-dev"


networks:
  microservices-net:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  mongo: {}

