parent=keycloak
import=common/keycloak

styles=css/styles.css

kcBodyClass=login-pf-page
kcLoginClass=login-pf-page__wrapper
kcFormCardClass=kc-form-card
kcFormCardAccountClass=kc-form-card__account
kcFormHeaderClass=kc-form-header
kcContentWrapperClass=kc-content-wrapper
kcLabelWrapperClass=kc-label-wrapper
kcFormGroupClass=form-group
kcLabelClass=kc-label
kcInputClass=pf-c-form-control
kcInputErrorMessageClass=kc-input-error-message
kcButtonClass=pf-c-button
kcButtonPrimaryClass=btn-primary
kcButtonBlockClass=btn-block
kcButtonLargeClass=btn-lg
kcSignUpClass=kc-sign-up
kcInfoAreaWrapperClass=kc-info-area-wrapper
kcLocaleWrapperClass=kc-locale-wrapper
